aliases:
    fleek-custom: micro ~/.local/share/fleek/nire-lysithea/custom.nix
    fleek-edit: micro ~/.fleek.yml
    fleek-user: micro ~/.local/share/fleek/user.nix
    fleeks: cd ~/.local/share/fleek
    latest-fleek-version: nix run https://getfleek.dev/latest.tar.gz -- version
    update-fleek: nix run https://getfleek.dev/latest.tar.gz -- update
allow_broken: false
auto_gc: true
bling: none
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:


    

    

    - asdf-vm





    - entr
    - diffutils
    
    - git # belongs in system packages
    - haskell-language-server

  

    # - tailscale



    - ripgrep

  
    - nanorc
    - 

    - zi
    - gimp
    - kitty-img
    - zoxide
    - tailscale

    - wl-clipboard-x11



    - rnix-lsp
    - nixfmt


    
    # - plocate # belongs in system packages
        
    
paths:
    - /usr/local
    - /usr/bin
    - /nix/var/nix/profiles/default/bin
    - $HOME/bin
    - $HOME/.local/bin
    - $HOME/.nix-profile/bin
    - $HOME/.zi/bin
    - $HOME/.config/zi/bin
    - $HOME/.config/emacs/bin
    - $HOME/.cargo/bin
programs:
    - dircolors
    - micro
    - zsh
    - python3
    - ruff
    - ruff-lsp
    - black

shell: zsh
systems:
    - arch: x86_64
      home: ""
      hostname: durandal
      os: linux
      user:
        email: nire@computernope.net
        name: Nire Bryce
        ssh_private_key_file: ~/.ssh/id_ed25519
        ssh_public_key_file: ~/.ssh/id_ed25519.pub
        username: elly
      username: elly
    - arch: x86_64
      home: ""
      hostname: nire-lysithea
      os: linux
      user:
        email: nire@computernope.net
        name: Nire Bryce
        ssh_private_key_file: ~/.ssh/id_ed25519
        ssh_public_key_file: ~/.ssh/id_ed25519.pub
        username: elly
      username: elly
    - arch: x86_64
      home: ""
      hostname: nire-galatea
      os: linux
      user:
        email: nire@computernope.net
        name: Nire Bryce
        ssh_private_key_file: ~/.ssh/id_ed25519
        ssh_public_key_file: ~/.ssh/id_ed25519.pub
        username: elly
      username: elly
track: nixos-unstable
unfree: true
users: []
